In [1]:
import pandas as pd
import requests

In [2]:
# json = requests.get("https://data.sfgov.org/resource/cuks-n6tp.json?$limit=10000")
#

In [26]:
# df = pd.DataFrame(json.json())
# df['location'][1]['coordinates']

[-122.41925789481357, 37.77514629165388]

In [3]:

df = pd.read_csv("zipcode.csv", sep=';')
df2 = pd.read_csv("census.csv")
states = pd.read_csv("states.csv", header=None, names=['Name', 'Abbr'])

In [4]:
gb = df.groupby("State").agg({"Latitude": "mean", "Longitude": "mean"})
gb = gb.reset_index()
gb = gb.rename(columns={"State": "Abbr"})
gb.tail(1)

   Abbr   Latitude   Longitude
53   WY  42.887224 -107.232956

In [18]:
newdf = pd.merge(df2, states, on='Name')
# df = df.rename(columns={"State": "Abbr"})
# donedf = pd.merge(newdf, df, on="Abbr", )
newdf = pd.merge(newdf, gb, on='Abbr')
newdf
lat = newdf['Latitude'].to_list()
lon = newdf['Longitude'].to_list()
names = newdf["Name"].to_list()
# heatarray = []
inc = newdf['Household Income'].to_list()
data = []
for x, item in enumerate(newdf["Longitude"]):
    data.append({"State": names[x], "location": [lat[x], lon[x]], "income": inc[x]})
data

[{'State': 'Alabama',
  'location': [32.859482801854035, -86.84384983545773],
  'income': 46472.0},
 {'State': 'Alaska',
  'location': [61.487933376383744, -152.49551165313642],
  'income': 76114.0},
 {'State': 'Arizona',
  'location': [33.625361104089265, -111.6907279330855],
  'income': 53510.0},
 {'State': 'Arkansas',
  'location': [35.11194386160107, -92.38092674898235],
  'income': 43813.0},
 {'State': 'California',
  'location': [36.14322517194392, -119.77399826435915],
  'income': 67169.0},
 {'State': 'Colorado',
  'location': [39.25645815441181, -105.29349037352928],
  'income': 65458.0},
 {'State': 'Connecticut',
  'location': [41.557624934537216, -72.81355222573357],
  'income': 73781.0},
 {'State': 'District of Columbia',
  'location': [38.89531540217382, -77.01958254710146],
  'income': 77649.0},
 {'State': 'Delaware',
  'location': [39.288821117647075, -75.52822093137257],
  'income': 63036.0},
 {'State': 'Florida',
  'location': [28.160068399204274, -82.02278675663142],
  'income': 50883.0},
 {'State': 'Georgia',
  'location': [33.04387886633166, -83.69556997085414],
  'income': 52977.0},
 {'State': 'Hawaii',
  'location': [21.988660087837854, -160.24180725675674],
  'income': 74923.0},
 {'State': 'Idaho',
  'location': [44.53219026706227, -114.86423627002975],
  'income': 50985.0},
 {'State': 'Illinois',
  'location': [40.413877929317714, -88.99676377504608],
  'income': 61229.0},
 {'State': 'Indiana',
  'location': [39.92696671802326, -86.28425005329447],
  'income': 52182.0},
 {'State': 'Iowa',
  'location': [42.03104158763838, -93.35259181088537],
  'income': 56570.0},
 {'State': 'Kansas',
  'location': [38.51669433706466, -97.13040319900489],
  'income': 55477.0},
 {'State': 'Kentucky',
  'location': [37.61321107558133, -84.81892687403098],
  'income': 46535.0},
 {'State': 'Maine',
  'location': [44.5807254435947, -69.43483486806882],
  'income': 53024.0},
 {'State': 'Louisiana',
  'location': [30.916454238410562, -91.71963621324498],
  'income': 46710.0},
 {'State': 'Massachusetts',
  'location': [42.23348925979113, -71.47053237989562],
  'income': 74167.0},
 {'State': 'Maryland',
  'location': [39.053842560897415, -76.76812641666672],
  'income': 78916.0},
 {'State': 'Michigan',
  'location': [43.45838622859511, -84.73934209226925],
  'income': 52668.0},
 {'State': 'Minnesota',
  'location': [45.56461866982925, -94.11585473339673],
  'income': 65699.0},
 {'State': 'Mississippi',
  'location': [32.82185521415608, -89.70477279128859],
  'income': 42009.0},
 {'State': 'Missouri',
  'location': [38.384826557295945, -92.45494306183016],
  'income': 51542.0},
 {'State': 'Montana',
  'location': [46.939255623501204, -110.30170605275788],
  'income': 50801.0},
 {'State': 'Nebraska',
  'location': [41.19567994034535, -98.17969038775527],
  'income': 56675.0},
 {'State': 'New Hampshire',
  'location': [43.38614288196721, -71.57137717704911],
  'income': 71305.0},
 {'State': 'Nevada',
  'location': [38.004132909482756, -116.73172182758626],
  'income': 55434.0},
 {'State': 'New Jersey',
  'location': [40.38912234514436, -74.5161411220472],
  'income': 76475.0},
 {'State': 'New Mexico',
  'location': [34.671712544217684, -106.15317122675752],
  'income': 46718.0},
 {'State': 'New York',
  'location': [42.19682294344584, -75.1173882661116],
  'income': 62765.0},
 {'State': 'North Carolina',
  'location': [35.572244836330974, -79.53905628147477],
  'income': 50320.0},
 {'State': 'North Dakota',
  'location': [47.51129792807424, -99.64736574013925],
  'income': 61285.0},
 {'State': 'Ohio',
  'location': [40.3883791061415, -82.74078830440604],
  'income': 52407.0},
 {'State': 'Oklahoma',
  'location': [35.51939973836473, -96.99869426918228],
  'income': 49767.0},
 {'State': 'Oregon',
  'location': [44.53234251515152, -122.07812879595954],
  'income': 56119.0},
 {'State': 'Pennsylvania',
  'location': [40.62703925738208, -77.55345841780509],
  'income': 56951.0},
 {'State': 'Rhode Island',
  'location': [41.70335632978724, -71.50914851063831],
  'income': 61043.0},
 {'State': 'South Carolina',
  'location': [33.95816643140795, -81.03302287184111],
  'income': 48781.0},
 {'State': 'South Dakota',
  'location': [44.30692547099766, -99.15341047099768],
  'income': 54126.0},
 {'State': 'Tennessee',
  'location': [35.794630906862736, -86.45657238602935],
  'income': 48708.0},
 {'State': 'Texas',
  'location': [31.277162801676777, -98.0631534779438],
  'income': 57051.0},
 {'State': 'Utah',
  'location': [39.92115921910115, -111.82478212640456],
  'income': 65325.0},
 {'State': 'Vermont',
  'location': [44.03341062269942, -72.6428141871166],
  'income': 57808.0},
 {'State': 'Virginia',
  'location': [37.712614309019635, -78.22690068941182],
  'income': 68766.0},
 {'State': 'West Virginia',
  'location': [38.46459070000004, -80.982546019149],
  'income': 44061.0},
 {'State': 'Washington',
  'location': [47.32874533242869, -121.17334842062408],
  'income': 66174.0},
 {'State': 'Wyoming',
  'location': [42.887223562814036, -107.23295582914571],
  'income': 60938.0},
 {'State': 'Wisconsin',
  'location': [44.105610487233996, -89.53277944893613],
  'income': 56759.0}]

In [13]:
newdf

,Unnamed: 0,Median Age,Population,Poverty Count,Household Income,Per Capita Income,Name,state,Abbr,Latitude,Longitude
0,1,38.7,4850771.0,849699.0,46472.0,25746.0,Alabama,1.0,AL,32.859483,-86.843850
1,2,33.9,738565.0,73380.0,76114.0,35065.0,Alaska,2.0,AK,61.487933,-152.495512
2,3,37.2,6809946.0,1128046.0,53510.0,27964.0,Arizona,4.0,AZ,33.625361,-111.690728
3,4,37.9,2977944.0,524211.0,43813.0,24426.0,Arkansas,5.0,AR,35.111944,-92.380927
4,5,36.1,38982847.0,5773408.0,67169.0,33128.0,California,6.0,CA,36.143225,-119.773998
5,6,36.5,5436519.0,612143.0,65458.0,34845.0,Colorado,8.0,CO,39.256458,-105.293490
6,7,40.8,3594478.0,350783.0,73781.0,41365.0,Connecticut,9.0,CT,41.557625,-72.813552
7,8,33.9,672391.0,111025.0,77649.0,50832.0,District of Columbia,11.0,DC,38.895315,-77.019583
8,9,39.8,943732.0,111304.0,63036.0,32625.0,Delaware,10.0,DE,39.288821,-75.528221
9,10,41.8,20278447.0,3070972.0,50883.0,28774.0,Florida,12.0,FL,28.160068,-82.022787
10,11,36.4,10201635.0,1679030.0,52977.0,28015.0,Georgia,13.0,GA,33.043879,-83.695570
11,12,38.8,1421658.0,143148.0,74923.0,32511.0,Hawaii,15.0,HI,21.988660,-160.241807
12,13,35.9,1657375.0,236000.0,50985.0,25471.0,Idaho,16.0,ID,44.532190,-114.864236
13,14,37.7,12854526.0,1698613.0,61229.0,32924.0,Illinois,17.0,IL,40.413878,-88.996764
14,15,37.5,6614418.0,933540.0,52182.0,27305.0,Indiana,18.0,IN,39.926967,-86.284250
15,16,38.1,3118102.0,361343.0,56570.0,30063.0,Iowa,19.0,IA,42.031042,-93.352592
16,17,36.3,2903820.0,361285.0,55477.0,29600.0,Kansas,20.0,KS,38.516694,-97.130403
17,18,38.6,4424376.0,783586.0,46535.0,25888.0,Kentucky,21.0,KY,37.613211,-84.818927
18,19,44.3,1330158.0,166904.0,53024.0,29886.0,Maine,23.0,ME,44.580725,-69.434835
19,20,36.4,4663461.0,887574.0,46710.0,26205.0,Louisiana,22.0,LA,30.916454,-91.719636
20,21,39.4,6789319.0,727546.0,74167.0,39913.0,Massachusetts,25.0,MA,42.233489,-71.470532
21,22,38.5,5996079.0,566966.0,78916.0,39070.0,Maryland,24.0,MD,39.053843,-76.768126
22,23,39.6,9925568.0,1510841.0,52668.0,28938.0,Michigan,26.0,MI,43.458386,-84.739342
23,24,37.9,5490726.0,560995.0,65699.0,34712.0,Minnesota,27.0,MN,45.564619,-94.115855
24,25,36.9,2986220.0,620007.0,42009.0,22500.0,Mississippi,28.0,MS,32.821855,-89.704773
25,26,38.4,6075300.0,861679.0,51542.0,28282.0,Missouri,29.0,MO,38.384827,-92.454943
26,27,39.8,1029862.0,144198.0,50801.0,28706.0,Montana,30.0,MT,46.939256,-110.301706
27,28,36.3,1893921.0,220330.0,56675.0,29866.0,Nebraska,31.0,NE,41.195680,-98.179690
28,29,42.7,1331848.0,104470.0,71305.0,36914.0,New Hampshire,33.0,NH,43.386143,-71.571377
29,30,37.7,2887725.0,405263.0,55434.0,28450.0,Nevada,32.0,NV,38.004133,-116.731722
30,31,39.6,8960161.0,938252.0,76475.0,39069.0,New Jersey,34.0,NJ,40.389122,-74.516141
31,32,37.3,2084828.0,420293.0,46718.0,25257.0,New Mexico,35.0,NM,34.671713,-106.153171
32,33,38.4,19798228.0,2908471.0,62765.0,35752.0,New York,36.0,NY,42.196823,-75.117388
33,34,38.4,10052564.0,1579871.0,50320.0,28123.0,North Carolina,37.0,NC,35.572245,-79.539056
34,35,35.1,745475.0,79374.0,61285.0,34256.0,North Dakota,38.0,ND,47.511298,-99.647366
35,36,39.3,11609756.0,1683890.0,52407.0,29011.0,Ohio,39.0,OH,40.388379,-82.740788
36,37,36.3,3896251.0,612714.0,49767.0,26461.0,Oklahoma,40.0,OK,35.519400,-96.998694
37,38,39.2,4025127.0,587248.0,56119.0,30410.0,Oregon,41.0,OR,44.532343,-122.078129
38,39,40.7,12790505.0,1623537.0,56951.0,31476.0,Pennsylvania,42.0,PA,40.627039,-77.553458
39,40,39.9,1056138.0,136126.0,61043.0,33315.0,Rhode Island,44.0,RI,41.703356,-71.509149
40,41,39.0,4893444.0,790657.0,48781.0,26645.0,South Carolina,45.0,SC,33.958166,-81.033023
41,42,36.8,855444.0,114885.0,54126.0,28761.0,South Dakota,46.0,SD,44.306925,-99.153410
42,43,38.6,6597381.0,1072360.0,48708.0,27277.0,Tennessee,47.0,TN,35.794631,-86.456572
43,44,34.3,27419612.0,4291384.0,57051.0,28985.0,Texas,48.0,TX,31.277163,-98.063153
44,45,30.5,2993941.0,324856.0,65325.0,26907.0,Utah,49.0,UT,39.921159,-111.824782
45,46,42.8,624636.0,68144.0,57808.0,31917.0,Vermont,50.0,VT,44.033411,-72.642814
46,47,38.0,8365952.0,906838.0,68766.0,36268.0,Virginia,51.0,VA,37.712614,-78.226901
47,48,42.2,1836843.0,317089.0,44061.0,24774.0,West Virginia,54.0,WV,38.464591,-80.982546
48,49,37.6,7169967.0,859950.0,66174.0,34869.0,Washington,53.0,WA,47.328745,-121.173348
49,50,37.0,583200.0,63398.0,60938.0,31214.0,Wyoming,56.0,WY,42.887224,-107.232956
50,51,39.2,5763217.0,692719.0,56759.0,30557.0,Wisconsin,55.0,WI,44.105610,-89.532779